/* Generated By:JavaCC: Do not edit this line. TrataPolinomiosConstants.java */
package TrataPolinomios;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TrataPolinomiosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int ELEVADO = 7;
  /** RegularExpression Id. */
  int TINDEPENDIENTE = 8;
  /** RegularExpression Id. */
  int ENTERO = 9;
  /** RegularExpression Id. */
  int DIGITO = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"x\"",
    "<ENTERO>",
    "<DIGITO>",
    "\";\"",
    "\".\"",
  };

}
